name: ci

on:
  push:
    paths:
      - 'src/**'
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      COMMIT_SHORT_SHA: ${{ steps.get_commit_sha.outputs.COMMIT_SHORT_SHA }}
    steps:
      -
       uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - 
        name: Get the last 7 characters of the git commit SHA
        run: |
          github_sha_hash=${{ github.sha }}
          github_sha_short="${github_sha_hash:0:7}"
          echo "COMMIT_SHORT_SHA=$github_sha_short" >> $GITHUB_ENV
          echo "COMMIT_SHORT_SHA=$github_sha_short" >> $GITHUB_OUTPUT

      - 
        name: Confirm git commit SHA output
        run: echo ${{ env.COMMIT_SHORT_SHA }}
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${{ env.COMMIT_SHORT_SHA }}
    
  
  cd:
    runs-on: self-hosted
    needs: ci
    env:
      COMMIT_SHORT_SHA: ${{ needs.ci.outputs.COMMIT_SHORT_SHA }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          mkdir -p "$RUNNER_TEMP/argocd"
          install -m 555 argocd-linux-amd64 "$RUNNER_TEMP/argocd/argocd"
          rm argocd-linux-amd64
          echo "$RUNNER_TEMP/argocd" >> "$GITHUB_PATH"
      - name: Setup yq
        env:
          VERSION: v4.2.0
          PLATFORM: linux_amd64
        run: |
          sudo apt update && sudo apt install -y wget
          sudo wget https://github.com/mikefarah/yq/releases/download/${VERSION}/yq_${PLATFORM}.tar.gz -O - |\
            sudo tar xz && sudo mv yq_${PLATFORM} /usr/local/bin/yq && sudo chmod +x /usr/local/bin/yq

      - name: Update the image tag in the Helm values file
        run: |
           sudo yq eval -i '.image.tag = $COMMIT_SHORT_SHA' charts/python-app/values.yaml

      - name: argocd sync
        env:
          ARGOCD_SERVER: argocd-server.argocd.svc.cluster.local
          ARGOCD_OPTS: --grpc-web --insecure 
        run: |
          set -x
          argocd version
          argocd login $ARGOCD_SERVER  --grpc-web --insecure  \
            --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd proj list
          argocd app list
          argocd app sync python-app
          echo "Deployed image with tag: $COMMIT_SHORT_SHA"
